# 1.1 Handling Missing Data

In [2]:
import pandas as pd
import numpy as np
string_data = pd.Series(['aardvark', 'artichoke', np.nan,'avocado'])

In [3]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

## Filling out Missing Data

In [7]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])

In [8]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data = pd.DataFrame([[1, 6.5, 3],[1, NA, NA], [NA, NA, NA], [NA, 6.5, 3]])

In [13]:
cleaned = data.dropna()

In [14]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [15]:
data.dropna(how = 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data[4] = NA

In [17]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [18]:
data.dropna(how = 'all', axis = 1)

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [19]:
df = pd.DataFrame(np.random.randn(7,3))
df.iloc[:4,1]= NA
df.iloc[:2,2] = NA

In [20]:
df

0         1         2
0 -1.110172       NaN       NaN
1 -0.151843       NaN       NaN
2 -1.104659       NaN  0.637960
3  0.279304       NaN  0.560206
4 -1.033468  0.314907  0.875760
5 -0.081981  0.336150 -1.177014
6  0.055683  0.509601 -0.298308

In [21]:
df.dropna()

0         1         2
4 -1.033468  0.314907  0.875760
5 -0.081981  0.336150 -1.177014
6  0.055683  0.509601 -0.298308

In [27]:
df.dropna(thresh = 2)

0         1         2
2 -1.104659       NaN  0.637960
3  0.279304       NaN  0.560206
4 -1.033468  0.314907  0.875760
5 -0.081981  0.336150 -1.177014
6  0.055683  0.509601 -0.298308

In [31]:
df.dropna(axis = 1)

0         1         2
0 -1.110172       NaN       NaN
1 -0.151843       NaN       NaN
2 -1.104659       NaN  0.637960
3  0.279304       NaN  0.560206
4 -1.033468  0.314907  0.875760
5 -0.081981  0.336150 -1.177014
6  0.055683  0.509601 -0.298308

## Fill in Missing Data

In [32]:
df

0         1         2
0 -1.110172       NaN       NaN
1 -0.151843       NaN       NaN
2 -1.104659       NaN  0.637960
3  0.279304       NaN  0.560206
4 -1.033468  0.314907  0.875760
5 -0.081981  0.336150 -1.177014
6  0.055683  0.509601 -0.298308

In [33]:
df.fillna(0)

0         1         2
0 -1.110172  0.000000  0.000000
1 -0.151843  0.000000  0.000000
2 -1.104659  0.000000  0.637960
3  0.279304  0.000000  0.560206
4 -1.033468  0.314907  0.875760
5 -0.081981  0.336150 -1.177014
6  0.055683  0.509601 -0.298308

In [34]:
df.fillna({1:0.5, 2:0})

0         1         2
0 -1.110172  0.500000  0.000000
1 -0.151843  0.500000  0.000000
2 -1.104659  0.500000  0.637960
3  0.279304  0.500000  0.560206
4 -1.033468  0.314907  0.875760
5 -0.081981  0.336150 -1.177014
6  0.055683  0.509601 -0.298308

In [35]:
df.fillna(0, inplace=True)

In [36]:
df

0         1         2
0 -1.110172  0.000000  0.000000
1 -0.151843  0.000000  0.000000
2 -1.104659  0.000000  0.637960
3  0.279304  0.000000  0.560206
4 -1.033468  0.314907  0.875760
5 -0.081981  0.336150 -1.177014
6  0.055683  0.509601 -0.298308

In [37]:
df = pd.DataFrame(np.random.randn(6,3))
df.iloc[2:,1] = NA
df.iloc[4:,2] = NA
df

0         1         2
0 -0.316492  0.034105 -1.205847
1 -1.991994  0.089128  0.538792
2 -2.238216       NaN -1.523761
3  1.523421       NaN -0.194036
4  2.078064       NaN       NaN
5 -0.438610       NaN       NaN

In [38]:
df.fillna(method='ffill')

0         1         2
0 -0.316492  0.034105 -1.205847
1 -1.991994  0.089128  0.538792
2 -2.238216  0.089128 -1.523761
3  1.523421  0.089128 -0.194036
4  2.078064  0.089128 -0.194036
5 -0.438610  0.089128 -0.194036

In [40]:
df.fillna(method = 'ffill', limit = 2)

0         1         2
0 -0.316492  0.034105 -1.205847
1 -1.991994  0.089128  0.538792
2 -2.238216  0.089128 -1.523761
3  1.523421  0.089128 -0.194036
4  2.078064       NaN -0.194036
5 -0.438610       NaN -0.194036

In [43]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [44]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

# 1.2 Data Transformation

## Removing Duplicates

In [47]:
data = pd.DataFrame({'k1': ['one','two']*3 + ['two'],
                    'k2': [1,1,2,3,3,4,4]})

In [48]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [49]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [50]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [51]:
data['v1'] = range(7)

In [52]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [53]:
data.drop_duplicates(['k1','k2'], keep = 'last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

## Transforming Data Using a Function or Mapping

In [54]:
data = pd.DataFrame({'food': ['bacon','pulled pork','bacon','Pastrami','corned beef',
                             'Bacon','pastrami','honey ham','nova lox'],
                    'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [55]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [66]:
meat_to_animal = {
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami':'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox':'salmon'
}

In [57]:
meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corn beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [59]:
lowercased = data['food'].str.lower()

In [60]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [61]:
data['animal'] = lowercased.map(meat_to_animal)

In [63]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     NaN
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [67]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

## Replacing Values

In [71]:
data = pd.Series([1., -999, 2., -999, -1000, 3])

In [72]:
data.replace(-999, NA)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [73]:
data.replace([-999,-1000], NA)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [74]:
data.replace([-999, -1000],[NA, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [76]:
data.replace({-999:NA, -1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

## Renaming Axis Indexes

In [79]:
data = pd.DataFrame(np.arange(12).reshape(3,4),
                   index = ['Ohio','Colorado','New York'],
                   columns = ['one','two','three','four'])

In [80]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [82]:
transform = lambda x: x[:4].upper()

In [83]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [84]:
data.index = data.index.map(transform)

In [85]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [87]:
data.rename(index = str.title, columns = str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [91]:
data.rename(index = {'OHIO':'INDIANA'},
           columns = {'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [92]:
data.rename(index = {'OHIO':'INDIANA'}, inplace = True)

In [93]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

# Discretization and Binning

In [94]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [95]:
bins = [18, 25, 35, 60, 100]

In [96]:
cats = pd.cut(ages, bins)

In [97]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [98]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [99]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [100]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [101]:
pd.cut(ages, [18, 26, 36, 61, 100], right = False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [102]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [103]:
pd.cut(ages,bins, labels = group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [114]:
data = np.random.rand(20)

In [115]:
data

array([0.10954589, 0.4282356 , 0.29314391, 0.50585405, 0.73590948,
       0.69662997, 0.70765371, 0.3572315 , 0.26835322, 0.88323404,
       0.36947265, 0.59638458, 0.99127023, 0.8824376 , 0.76132255,
       0.42419193, 0.84110694, 0.63142453, 0.42737383, 0.45334446])

In [116]:
pd.cut(data, 4, precision = 2)

[(0.11, 0.33], (0.33, 0.55], (0.11, 0.33], (0.33, 0.55], (0.55, 0.77], ..., (0.33, 0.55], (0.77, 0.99], (0.55, 0.77], (0.33, 0.55], (0.33, 0.55]]
Length: 20
Categories (4, interval[float64]): [(0.11, 0.33] < (0.33, 0.55] < (0.55, 0.77] < (0.77, 0.99]]

In [117]:
pd.value_counts(pd.cut(data, 4, precision = 2))

(0.33, 0.55]    7
(0.55, 0.77]    6
(0.77, 0.99]    4
(0.11, 0.33]    3
dtype: int64

In [121]:
data = np.random.randn(1000)

In [122]:
cats = pd.qcut(data, 4)

In [123]:
cats

[(-0.767, -0.0651], (0.679, 2.831], (0.679, 2.831], (-0.0651, 0.679], (-3.465, -0.767], ..., (-0.767, -0.0651], (-0.0651, 0.679], (0.679, 2.831], (0.679, 2.831], (-3.465, -0.767]]
Length: 1000
Categories (4, interval[float64]): [(-3.465, -0.767] < (-0.767, -0.0651] < (-0.0651, 0.679] < (0.679, 2.831]]

In [124]:
pd.value_counts(cats)

(0.679, 2.831]       250
(-0.0651, 0.679]     250
(-0.767, -0.0651]    250
(-3.465, -0.767]     250
dtype: int64

pd.cut cut the arrays in equal lenth while pd.qcut cut the arrays in equal number

In [125]:
cats = pd.qcut(data, [0, 0.1, 0.5, 0.9, 1])

In [126]:
pd.value_counts(cats)

(-0.0651, 1.297]     400
(-1.387, -0.0651]    400
(1.297, 2.831]       100
(-3.465, -1.387]     100
dtype: int64

## Detecting and Filtering Outliers

In [127]:
data = pd.DataFrame(np.random.randn(1000,4))

In [128]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.040794    -0.002844    -0.030671     0.024080
std       0.980135     1.042738     0.998933     1.007848
min      -3.592826    -2.979460    -3.587061    -3.037512
25%      -0.678753    -0.720676    -0.702245    -0.657844
50%      -0.062229    -0.023743    -0.014872     0.033245
75%       0.597376     0.706535     0.657384     0.699559
max       3.140308     3.457565     3.376704     3.631676

In [130]:
col = data[2]

In [131]:
col[np.abs(col) > 3]

35    -3.009337
365   -3.587061
426    3.312201
538   -3.150851
732    3.370096
777    3.376704
Name: 2, dtype: float64

In [136]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
0   -3.067015 -0.391451  0.663007  0.003062
20  -3.012187  1.360805  1.174366 -0.564508
35   1.057719  0.507142 -3.009337 -1.670292
193  3.038253  1.569063  0.221761  0.167104
353  0.313047 -0.015002  0.826993 -3.037512
365 -0.652744 -0.277249 -3.587061  0.216166
426  0.395377  1.723423  3.312201 -1.287534
538 -1.681654 -1.082269 -3.150851 -0.353584
591  0.764507  3.457565 -1.052640 -1.078768
615  0.007926 -0.050044  0.614967  3.078109
732  1.200300  0.096265  3.370096 -0.349797
767  3.140308  1.697728 -1.173238 -1.457479
777 -0.600425 -1.184010  3.376704 -0.910580
816 -3.592826 -0.509185 -1.375460  2.004588
847 -0.815739  2.097092  0.483748  3.631676
902 -0.106072  3.110223 -1.199783  0.302376

In [139]:
data[np.abs(data)>3] = np.sign(data)*3

In [140]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.040300    -0.003412    -0.030982     0.023408
std       0.977353     1.040993     0.993103     1.005432
min      -3.000000    -2.979460    -3.000000    -3.000000
25%      -0.678753    -0.720676    -0.702245    -0.657844
50%      -0.062229    -0.023743    -0.014872     0.033245
75%       0.597376     0.706535     0.657384     0.699559
max       3.000000     3.000000     3.000000     3.000000

## Permutation and Random Sampling

In [142]:
df = pd.DataFrame(np.arange(5*4).reshape(5,4))

In [143]:
sampler = np.random.permutation(5)

In [144]:
sampler

array([3, 0, 4, 1, 2])

In [145]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
0   0   1   2   3
4  16  17  18  19
1   4   5   6   7
2   8   9  10  11

In [146]:
df.sample(n = 3)

0  1   2   3
1  4  5   6   7
2  8  9  10  11
0  0  1   2   3

In [147]:
df.sample(n=6, replace =True)

0   1   2   3
4  16  17  18  19
0   0   1   2   3
1   4   5   6   7
0   0   1   2   3
4  16  17  18  19
4  16  17  18  19

## Computing Indicator/Dummy Variables

In [148]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'],
                  
                  'data1': range(6)})

In [149]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [150]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [151]:
dummies = pd.get_dummies(df['key'], prefix = 'key')

In [155]:
df_with_dummy = df[['data1']].join(dummies)

In [156]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [157]:
np.random.seed(12345)

In [158]:
values = np.random.rand(10)

In [159]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [160]:
bins = [0,0.2, 0.4, 0.6, 0.8,1]

In [161]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

# 1.3 String Manipulation

## String object Methods

In [163]:
val = 'a,b, guido'
val.split(',')

['a', 'b', ' guido']

In [164]:
pieces = [x.strip() for x in val.split(',')]

In [165]:
pieces

['a', 'b', 'guido']

In [167]:
first, second, third = pieces
first+'::'+second+'::'+third

'a::b::guido'

In [168]:
'::'.join(pieces)

'a::b::guido'

In [169]:
'guido' in val

True

In [170]:
val.index(',')

1

In [171]:
val.find(':')

-1

In [172]:
val.index(':')

ValueError: substring not found

**Note the differences between find and index is that index raises an exception if the string isn't found versus returning -1 in find**

In [173]:
val.count(',')

2

In [174]:
val.replace(',','::')

'a::b:: guido'

In [175]:
val

'a,b, guido'

In [176]:
val.replace(',','')

'ab guido'

In [177]:
val.lower()

'a,b, guido'

In [178]:
val.upper()

'A,B, GUIDO'

## Regular Expressions

In [179]:
import re

In [180]:
text = 'foo   bar\t bax \tqux'

In [181]:
text

'foo   bar\t bax \tqux'

In [182]:
re.split('\s+', text)

['foo', 'bar', 'bax', 'qux']

In [183]:
regex= re.compile('\s+')

In [184]:
regex.split(text)

['foo', 'bar', 'bax', 'qux']

In [185]:
regex.findall(text)

['   ', '\t ', ' \t']

In [186]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [187]:
regex = re.compile(pattern, flags = re.IGNORECASE)

In [188]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

**search returns a special match object for the first email address in the text**

In [189]:
m = regex.search(text)

<re.Match object; span=(5, 20), match='dave@google.com'>


In [191]:
text[m.start():m.end()]

'dave@google.com'

**match will only return true if the pattern occurs at the start of the string**

In [194]:
print(regex.match(text))

None


In [196]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



**suppose you wanted to find email address and simultaneously segment each address into its three components: username, domain name, and domain suffix. To do this, put parentheses around the parts of the pattern to segment:**

In [197]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [198]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [208]:
m = regex.match('wesm@youtube.com')

In [209]:
m.groups()

('wesm', 'youtube', 'com')

In [210]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [211]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



In [212]:
data = pd.Series({'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com', 'Rob': 'rob@gmail.com', 'Wes': NA})

In [213]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [214]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [216]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [217]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [218]:
data.str.findall(pattern, flags = re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [219]:
matches = data.str.match(pattern, flags = re.IGNORECASE)

In [220]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [221]:
matches.str.get(1)

Dave    NaN
Steve   NaN
Rob     NaN
Wes     NaN
dtype: float64

In [222]:
data.str[1:]

Dave     ave@google.com
Steve    teve@gmail.com
Rob        ob@gmail.com
Wes                 NaN
dtype: object