In [19]:
import pandas as pd
import numpy as np

In [2]:
from pandas import Series, DataFrame

# 1.1 Introduction to pandas Data Structures

## 1.1.1 Series

In [5]:
obj = pd.Series([4,7, -5,3])

In [6]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [7]:
obj.values

array([ 4,  7, -5,  3])

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = pd.Series([4,7,-5,3], index = ['d','b','c','a'])

In [10]:
obj2

d    4
b    7
c   -5
a    3
dtype: int64

In [11]:
obj2.index

Index(['d', 'b', 'c', 'a'], dtype='object')

In [12]:
obj2['a']

3

In [13]:
obj2['d']

4

In [14]:
obj2['d'] = 5

In [15]:
obj2[['a','d','b']]

a    3
d    5
b    7
dtype: int64

In [16]:
obj2[obj2>0]

d    5
b    7
a    3
dtype: int64

In [17]:
obj2*2

d    10
b    14
c   -10
a     6
dtype: int64

In [20]:
np.exp(obj2)

d     148.413159
b    1096.633158
c       0.006738
a      20.085537
dtype: float64

In [21]:
'b' in obj2

True

In [22]:
'e' in obj2

False

In [23]:
sdata = {'Ohio': 35000, 'Texas':71000, 'Oregon': 16000, 'Utah': 5000}

In [24]:
obj3 = pd.Series(sdata)

In [25]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [26]:
states = ['California','Ohio','Oregon', 'Texas']

In [27]:
obj4 = pd.Series(sdata, index = states)

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [31]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [34]:
obj4.name = 'population'

In [36]:
obj4.index.name = 'state'

In [37]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [38]:
obj


0    4
1    7
2   -5
3    3
dtype: int64

In [39]:
obj.index = ['Bob','Joe','Jeff','Ryan']

In [40]:
obj

Bob     4
Joe     7
Jeff   -5
Ryan    3
dtype: int64

## 1.1.2 DataFrame

In [41]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [42]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [43]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [44]:
pd.DataFrame(data, columns = ['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [45]:
frame2 = pd.DataFrame(data, columns = ['year','state','pop','debt'], index = ['one','two','three','four','five','six'])

In [46]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [47]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [48]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [49]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [50]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [51]:
frame2.debt = 16.5

In [52]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [55]:
frame2['debt'] = np.arange(6)

In [56]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [57]:
val = pd.Series([-1.2,-1.5,-1.7], index = ['two','four','five'])

In [58]:
frame2['debt'] = val

In [59]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [60]:
frame2['eastern'] = frame2.state == 'Ohio'

In [61]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [62]:
del frame2['eastern']

In [63]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [64]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [65]:
frame3 = pd.DataFrame(pop)

In [66]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [67]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [73]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [74]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [75]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [76]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [78]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## 1.1.3 Index Objects

In [79]:
obj = pd.Series(range(3), index = ['a','b','c'])

In [80]:
index = obj.index

In [81]:
index

Index(['a', 'b', 'c'], dtype='object')

In [82]:
index[1:]

Index(['b', 'c'], dtype='object')

In [83]:
labels = pd.Index(np.arange(3))

In [84]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [85]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)

In [86]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [87]:
obj2.index is labels

True

In [88]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [89]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [91]:
'Ohio' in frame3.columns

True

In [92]:
2002 in frame3.index

True

In [93]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [94]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# 1.2 Essential Functionality

## 1.2.1 Reindexing

In [95]:
obj = pd.Series([4.5,7.2,-5.3,3.6], index = ['d','b','a','c'])

In [96]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [98]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [99]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [100]:
obj3 = pd.Series(['blue','purple','yellow'], index = [0,2,4])

In [101]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [102]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [103]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index = ['a','c','d'],
                    columns = ['Ohio','Texas','California'])

In [104]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [105]:
frame2 = frame.reindex(['a','b','c','d'])

In [106]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [107]:
states = ['Texas','Utah','California']

In [108]:
frame3 = frame.reindex(columns = states)

In [109]:
frame3

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

## 1.2.2 Dropping Entries from an Axis

In [111]:
obj = pd.Series(np.arange(5), index = ['a','b','c','d','e'])

In [112]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [113]:
new_obj = obj.drop('c')

In [114]:
new_obj

a    0
b    1
d    3
e    4
dtype: int64

In [116]:
obj.drop(['d','c'])

a    0
b    1
e    4
dtype: int64

In [117]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [118]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [122]:
data.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [120]:
data.drop(['two','four'], axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [123]:
obj.drop('c', inplace = True)

In [124]:
obj

a    0
b    1
d    3
e    4
dtype: int64

In [125]:
ser = pd.Series(np.arange(3.))

In [126]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [128]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [129]:
ser2[-1]

2.0

In [130]:
ser[:1]

0    0.0
dtype: float64

In [131]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [132]:
ser.iloc[:1]

0    0.0
dtype: float64